### PR TITLE
factor out a common tsconfig.json

### PR DESCRIPTION
**Pull request by trevj**
Now we have separate `tsconfig.json` files for each "top-level" directory, we can have the nice things (here, at least).

### CODE REVIEW

**Comment by trevj** [comment]
@alalamav I discovered "configuration inheritance" and I think it can work well for us:
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

Right now `www/` has to override a few things but otherwise this is useful. Also, move to a proper `types/` directory. If you can think of a better name for `src/ambient/` for the Cordova ambient declarations, I'm open to suggestions :-)

**Comment by alalamav** [comment]
Nice! Why are we separating the Cordova typings from the rest? For consistency, could we put them in `src/types/[outline|cordova]/`?

**Comment by trevj** [comment]
@alalamav We could totally do that. I separated them only because these are "ambient" typings rather than for modules. Happy to change if you like, I'm all in favour of fewer top-level directories myself.

**Comment by alalamav** [comment]
Got it! I think having the typing files in a single directory is clearer. To your point of distinguishing module typings from our own, how about we put them in `src/types/ambient`?

**Comment by trevj** [comment]
OK, done. I had to move the module `.d.ts` files into their own tree and update the top-level `tconfig.json`, otherwise the compiler wasn't happy - but this looks good to me.

**Pull request merged**
