### PR TITLE
fix(build): 🚧 fix `buildMode` typo in cordova build script

### PR DESCRIPTION
**Pull request by jyyi1**

### CODE REVIEW

**Comment by jyyi1** [comment]
+ @kevindamm-jigsaw for awareness cuz it might affect the release.

**Review by fortuna — APPROVED** [review]
Oh no! Did we release a debug version?

It would be nice if platform and buildMode were objects instead so we could do platform.isAndroid() or buildMode.isRelease().

If this was Typescript than we could have types like "debug" | "release"

**Comment by jyyi1** [comment]
> Oh no! Did we release a debug version?
> 
> It would be nice if platform and buildMode were objects instead so we could do platform.isAndroid() or buildMode.isRelease().
> 
> If this was Typescript than we could have types like "debug" | "release"

I think so 😟, our [most recent release is about 3 months ago](https://github.com/Jigsaw-Code/outline-releases/blob/master/client/Outline.apk), the code has been there for 5 months.

**Comment by daniellacosse** [comment]
Whoops 😞 - my bad...

**Pull request merged**
