### PR TITLE
⬆️ build(deps): update CocoaLumberjack to support XCode 13

### PR DESCRIPTION
**Pull request by jyyi1**
Currently CocoaLumberjack does not support XCode 13, it will provide the following error:

> module compiled with Swift 5.4.2 cannot be imported by the Swift 5.5.1 compiler

This is because CocoaLumberjack does not support Swift 5.5 until [CocoaLumberjack 3.7.3](https://github.com/CocoaLumberjack/CocoaLumberjack/releases/tag/3.7.3). In this change set, I upgrade it to the latest [CocoaLumberjack 3.7.4](https://github.com/CocoaLumberjack/CocoaLumberjack/releases/tag/3.7.4) by using carthage:

```
carthage update --platform macOS
carthage update --platform iOS --use-xcframeworks
```

### CODE REVIEW

**Review by fortuna — COMMENTED** [review]
Could you update the Github action to use the right Xcode? The tests are not passing because of incompatibility the other way:
```
module compiled with Swift 5.5.2 cannot be imported by the Swift 5.4.2 compiler
```

Also, shouldn't we be using the xcframework instead?

**Comment by fortuna** [comment]
I think we need to fix:
- https://github.com/Jigsaw-Code/outline-client/blob/master/.github/workflows/build_and_test.yml#L93
- https://github.com/Jigsaw-Code/outline-client/blob/master/.github/workflows/build_and_test.yml#L120

**Comment by jyyi1** [comment]
> Could you update the Github action to use the right Xcode? The tests are not passing because of incompatibility the other way:
> 
> ```
> module compiled with Swift 5.5.2 cannot be imported by the Swift 5.4.2 compiler
> ```
> 
> Also, shouldn't we be using the xcframework instead?

xcframework requires changes to XCode project, we need to use another PR if we would like to do so.

**Review by fortuna — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
