### PR TITLE
Reverse connection animation motion

### PR DESCRIPTION
**Pull request by JonathanDCohen**
This fixes a pet peeve of mine: the connecting animation goes the wrong
way for what a radar sweep should look like!  Now the light part trails
the motion instead of leads it.

Video showing new rotation:

[Demonstration of animation](https://youtu.be/9WIVgDHZces)

### CODE REVIEW

**Comment by alalamav** [comment]
IMO, the animation's purpose is to give the user an indication of progress while waiting. The clockwise rotation is aligned with the passage of time. Another way to look at it: connecting is analogous to tightening a cap, which also follows clockwise motion. Not sure the intention was to mimick a radar.

**Comment by JonathanDCohen** [comment]
Closed.  And @smithmonique It was all of 5 minutes of work, which is why I just sent it off :)

**Comment by JonathanDCohen** [comment]
@smithmonique Does Vini's suggestion of horizontally flipping the image so that it's still rotating clockwise and the light is trailing?  This has the added benefit of making the cards consistent with the Outline logo -- right now they're mirrored

**Comment by smithmonique** [comment]
Could I see what that looks like before signing off? Would it be quick/easy
to prototype?

Thanks!
Monique

**Comment by JonathanDCohen** [comment]
@smithmonique https://youtu.be/MaLKDOUQV2M

The screen recorder glitched out a bit at the end but this should be good enough to show you what it looks like

**Comment by smithmonique** [comment]
Love it, looks great. Thanks!

**Pull request closed without merging**
