### PR TITLE
feat(client): use alert only for custom provider error

### PR DESCRIPTION
**Pull request by daniellacosse**

### CODE REVIEW

**Review by sbruens — APPROVED** [review]
I don't know what @fortuna had in mind, but this LGTM.

**Review by fortuna — APPROVED** [review]

**Review by fortuna — CHANGES_REQUESTED** [review]
Wait, what is the experience here? Are we not showing the error toast anymore?

**Review by fortuna — COMMENTED** [review]
This diverges from the usual error handling. Why not show the regular toast, with details?

**Review by fortuna — CHANGES_REQUESTED** [review]
How are you showing the details?
I meant in the other PR to show the toast with the message, as we do with all errors, but the details on the alert.

**Pull request closed without merging**
