### PR TITLE
CI build for Linux, Windows, MacOS and Android (master)

### PR DESCRIPTION
**Pull request by daniellacosse**
Ah, I accidentally forgot to change the base branch before merging this the first time.

Also, we need to change the branch protection rules.

---

--> Blocks https://github.com/Jigsaw-Code/outline-client/pull/1109

### CODE REVIEW

**Comment by bemasc** [comment]
OK, this is a verbatim respin of #1096, which is already approved, so feel free to merge once CI passes.

**Review by bemasc — APPROVED** [review]

**Comment by daniellacosse** [comment]
> OK, this is a verbatim respin of #1096, which is already approved, so feel free to merge once CI passes.

Ah, it did pass, we just need to change the `Required` branch protection checks as they've been split out into the various builds. Do you have permission to do so?

**Comment by bemasc** [comment]
> > OK, this is a verbatim respin of #1096, which is already approved, so feel free to merge once CI passes.
> 
> Ah, it did pass, we just need to change the `Required` branch protection checks as they've been split out into the various builds. Do you have permission to do so?

I think so.  What do you want to be `Required`?

**Comment by daniellacosse** [comment]
> > > OK, this is a verbatim respin of #1096, which is already approved, so feel free to merge once CI passes.
> > 
> > 
> > Ah, it did pass, we just need to change the `Required` branch protection checks as they've been split out into the various builds. Do you have permission to do so?
> 
> I think so. What do you want to be `Required`?

Either `Build and Test / Linux` as that also runs the tests (I split these concerns up in a later PR) or all of them: `Build and Test / Linux` `Build and Test / Windows` `Build and Test / MacOS` `Build and Test / Android`. Your choice

**Pull request merged**
