### PR TITLE
chore(www): improve error messaging and update zero-state footer to point to the Manager

### PR DESCRIPTION
**Pull request by daniellacosse**

### CODE REVIEW

**Review by maddyhof — APPROVED** [review]
LGTM

**Review by fortuna — COMMENTED** [review]
I only see the changes to the messages.
Perhaps also update the PR title to be clearer.

**Review by maddyhof — APPROVED** [review]
LGTM

**Review by fortuna — APPROVED** [review]

**Comment by hilary-ops** [comment]
LGTM

**Pull request merged**
