### PR TITLE
chore: allow GitHub to search build folders

### PR DESCRIPTION
**Pull request by joeytwiddle**
By default, GitHub excludes `build/` folders from [some searches](https://support.github.com/ticket/personal/0/1954062), such as the `t` search on GItHub's website. This makes sense in many projects.

However, Outline's `/*/build/` folders contain scripts, not build artefacts (which in Outline appear under `/output/` - although formerly `/build/`)

This change will allow github to search Outline's `build/` folders, as with most other folders.

(Docs on `linguist` attributes [here](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md).)

To test:
- On the [repo's GitHub page](https://github.com/JigSaw-Code/outline-client/), press `t` and then try a search for `download_file`. You will get 0 results.
- Try the same on [this PR's branch](https://github.com/joeytwiddle/outline-client/tree/patch-2). You should see a result!

### CODE REVIEW

**Comment by joeytwiddle** [comment]
Note, I tried to be explicit about the folders I wanted to whitelist, by doing:

```
/src/build/** linguist-generated=false
/tools/build/** linguist-generated=false
```

or by doing

```
build/** linguist-generated=false
```

in `/src/.gitattributes` and `/tools/.gitattributes`

However neither of those approaches worked.

The disadvantage of the current approach is that, if the repo is ever given a `/build` folder, GitHub will be able to search it!

**Review by fortuna — APPROVED** [review]
Thanks for the contribution. It's great when people that know these things help us!

**Review by jyyi1 — APPROVED** [review]

**Comment by joeytwiddle** [comment]
Added a comment to the `.gitattributes` file, explaining the reason for the line

**Comment by fortuna** [comment]
Thanks for the comment. The tests were failing on master, but it's now fixed and we'll be able to submit once the tests pass.

**Pull request merged**
