### PR TITLE
fix #109

### LINKED ISSUE #109: cygwin required on Windows
I get the following error when trying to build the client on Windows. I'm running Windows 10 Professional April 2018 Update. The installation is relatively fresh (4-6 weeks old) and I did indeed run the yarn command before attempting to build.

```
C:\Users\REDACTED\Documents\outline-client>yarn do electron/build
yarn run v1.6.0
(node:3964) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ bash ./scripts/do_action.sh electron/build
./scripts/do_action.sh: line 16: $'\r': command not found
: invalid optionion.sh: line 17: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./scripts/do_action.sh: line 18: $'\r': command not found
./scripts/do_action.sh: line 21: $'\r': command not found
./scripts/do_action.sh: line 22: syntax error near unexpected token `$'{\r''
'/scripts/do_action.sh: line 22: `function do_action() {
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### PR DESCRIPTION
**Pull request by lgg**
add info about rsync and building outline-client on Windows

### CODE REVIEW

**Comment by alalamav** [comment]
@lgg, seems like there's an issue with the CLA. Would you mind signing again and adding a comment so I can merge this PR? Thanks.

**Comment by lgg** [comment]
@googlebot I signed it!

**Comment by lgg** [comment]
@googlebot I signed it!

**Comment by lgg** [comment]
@alalamav done!

**Comment by trevj** [comment]
@lgg Thanks for the fix!

**Pull request merged**
