### PR TITLE
add quotes to $ROOT_DIR in case of bad chars

### PR DESCRIPTION
**Pull request by daniellacosse**
I have a bit of a wacky file system setup where my folders contain strange characters - spaces and parentheses, etc. In order to support building the client on my machine, I had to wrap all instances of `$ROOT_DIR` and vars derived from `$ROOT_DIR` in double quotes to escape these characters. Doing so I am now able to run `do_action.sh` successfully.

### CODE REVIEW

**Comment by daniellacosse** [comment]
> @googlebot I signed it!

@googlebot I signed it!

**Review by alalamav — APPROVED** [review]
Thank you for the improvement, @daniellacosse

**Review by fortuna — APPROVED** [review]
Hi there! Thanks for the improvement!

**Comment by fortuna** [comment]
@daniellacosse We are having issues with Travis CI, which is blocking the merge of this PR. We are investigating.

**Comment by alalamav** [comment]
Hi @daniellacosse, it seems like the test github action got stuck so we can't merge this PR. Could you try pushing a new commit or ammending an existing one (force push) to see if that triggers the action?

**Comment by daniellacosse** [comment]
> Hi @daniellacosse, it seems like the test github action got stuck so we can't merge this PR. Could you try pushing a new commit or ammending an existing one (force push) to see if that triggers the action?

Apologies, just coming back from vacation. Glad this was able to be resolved!

**Pull request merged**
